[package]
name = "video"
version = "0.1.0"
edition = "2021"

[dependencies]
tdriver = { path = "../tdriver" }

[profile.release]
panic = "abort"
# Use either 2, 3, s or z
opt-level = 3
overflow-checks = false
lto = true

