name: Rust Apps
run-name: Rust Apps
on: 
  push:
    paths:
      - 'app/**'
    branches:
    - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout computerraria
      uses: actions/checkout@v3

    - name: Build
      run: |
        rustup target add riscv32i-unknown-none-elf
        for i in app/* ; do
          if [ -d "$i" ]; then
            echo "::group::$i"
            cargo build --verbose --manifest-path="$i/Cargo.toml"
            cargo build --target=riscv32i-unknown-none-elf --verbose --manifest-path="$i/Cargo.toml"
            echo "::endgroup"
          fi
        done


